# Prometheus Configuration for RSE Scheduler Orchestrator
# Monitors scheduler metrics, job execution, and system health

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'rse-scheduler'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configuration
scrape_configs:
  # RSE Scheduler Orchestrator metrics
  - job_name: 'rse-scheduler'
    static_configs:
      - targets: ['rse-scheduler:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node Exporter for system metrics (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker metrics (if available)
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 30s

  # Redis metrics (if available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Application health checks
  - job_name: 'rse-scheduler-health'
    static_configs:
      - targets: ['rse-scheduler:9090']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Custom job metrics endpoints
  - job_name: 'rse-jobs'
    static_configs:
      - targets: ['rse-scheduler:9090']
    metrics_path: '/job-metrics'
    scrape_interval: 60s

# Remote write configuration (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration (optional)
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"