name: Playwright E2E

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  node-lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

  e2e:
    if: ${{ vars.RUN_E2E == 'true' || github.event_name == 'workflow_dispatch' }}
    needs: [node-lint-and-build]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm i -D @playwright/test
          npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          UI_BASE_URL: http://localhost:3000
          PW_AUTH_STRATEGY: api
          # Optional creds for context saving (set repo secrets/variables to use)
          TEST_EMAIL: ${{ secrets.E2E_EMAIL }}
          TEST_PASSWORD: ${{ secrets.E2E_PASSWORD }}
          TEST_ADMIN_EMAIL: ${{ secrets.E2E_ADMIN_EMAIL }}
          TEST_ADMIN_PASSWORD: ${{ secrets.E2E_ADMIN_PASSWORD }}
          PW_ROLES: user,admin
        run: |
          # Prune stale storage older than TTL (default 24h)
          TTL_HOURS=${PW_STORAGE_TTL_HOURS:-24}
          if [ -d tests/.auth ]; then
            find tests/.auth -type f -mmin +$((TTL_HOURS*60)) -print -delete || true
          fi
          npx playwright test --config=tests/playwright.config.ts

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
